export type CategoryKey = "table" | "bench" | "bed";

export interface Product {
  id: number;
  slug: string;
  name: string;
  summary: string;
  price: number;
  discount: number | null;
  configurable: boolean;
  image: string;
  kante: string;
  gestell: string;
  lack: string;
  buerstung: string;
}

export type FilterKey = "kante" | "gestell" | "lack" | "buerstung";

export const categories = {
  table: {
    label: "Tische",
    eyebrow: "Massivholz Kollektion",
    description:
      "Esstische und Solitare mit ruhiger Proportion, klarer Kante und einer Materialprasenz, die auf Dauer angelegt ist.",
    heroImage: "/images/home/table1.png",
  },
  bench: {
    label: "Bänke",
    eyebrow: "Sitzobjekte",
    description:
      "Bänke fur Essbereich, Flur und Wohnraum, robust konstruiert und in einer klaren, zeitlosen Formensprache gehalten.",
    heroImage: "/images/products/Product9.jpg",
  },
  bed: {
    label: "Betten",
    eyebrow: "Schlafsysteme",
    description:
      "Betten aus Holz mit reduzierter Linie, warmer Oberflache und einer Konstruktion, die Material und Ruhe in den Mittelpunkt stellt.",
    heroImage: "/images/products/Product8.jpg",
  },
} as const satisfies Record<
  CategoryKey,
  { label: string; eyebrow: string; description: string; heroImage: string }
>;

export const catalog: Record<CategoryKey, Product[]> = {
  table: [
    {
      id: 1,
      slug: "wix-tisch",
      name: "Wix Tisch",
      summary: "Baumkante, dunkles Gestell und ruhige Tafelform.",
      price: 4890,
      discount: 12,
      configurable: false,
      image: "/images/products/Product11.png",
      kante: "Baumkante",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Gebürstet",
    },
    {
      id: 2,
      slug: "tafel-nord",
      name: "Tafel Nord",
      summary: "Lange Platte fur grosszugige Essbereiche.",
      price: 5290,
      discount: null,
      configurable: false,
      image: "/images/products/Product10.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Seidenmatt",
      buerstung: "Fein",
    },
    {
      id: 3,
      slug: "atelier-tisch",
      name: "Atelier Tisch",
      summary: "Klar gezeichneter Tisch mit leichterem Ausdruck.",
      price: 4580,
      discount: null,
      configurable: false,
      image: "/images/home/table2.png",
      kante: "Gerade",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Fein",
    },
    {
      id: 4,
      slug: "tisch-form",
      name: "Tisch Form",
      summary: "Essplatz mit leichter Platte und warmer Oberflache.",
      price: 4720,
      discount: 8,
      configurable: false,
      image: "/images/products/Product1.png",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Geölt",
      buerstung: "Fein",
    },
    {
      id: 5,
      slug: "esstisch-atelier",
      name: "Esstisch Atelier",
      summary: "Kompakter Tisch fur ruhig komponierte Wohnsituationen.",
      price: 4380,
      discount: null,
      configurable: false,
      image: "/images/products/Product2.jpg",
      kante: "Baumkante",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Gebürstet",
    },
    {
      id: 6,
      slug: "tafel-werk",
      name: "Tafel Werk",
      summary: "Massive Platte mit handwerklicher Anmutung und klarer Linie.",
      price: 5560,
      discount: 15,
      configurable: false,
      image: "/images/home/64596.jpg",
      kante: "Baumkante",
      gestell: "Natur",
      lack: "Seidenmatt",
      buerstung: "Gebürstet",
    },
  ],
  bench: [
    {
      id: 7,
      slug: "bank-linie",
      name: "Bank Linie",
      summary: "Lange Sitzbank mit klarer Basis und ruhigem Aufbau.",
      price: 2190,
      discount: null,
      configurable: false,
      image: "/images/products/Product9.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Matt",
      buerstung: "Gebürstet",
    },
    {
      id: 8,
      slug: "sitzbank-atelier",
      name: "Sitzbank Atelier",
      summary: "Warmer Holzton und leichte handwerkliche Note.",
      price: 1960,
      discount: 10,
      configurable: false,
      image: "/images/products/Product11.png",
      kante: "Baumkante",
      gestell: "Schwarz",
      lack: "Geölt",
      buerstung: "Fein",
    },
    {
      id: 9,
      slug: "polsterbank",
      name: "Polsterbank",
      summary: "Fur Essplatz und Nische, weich und robust kombiniert.",
      price: 2480,
      discount: null,
      configurable: false,
      image: "/images/products/Product8.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Seidenmatt",
      buerstung: "Gebürstet",
    },
    {
      id: 10,
      slug: "bank-nord",
      name: "Bank Nord",
      summary: "Schlanke Sitzbank fur Flur, Essplatz und ruhige Zwischenraume.",
      price: 1820,
      discount: 14,
      configurable: false,
      image: "/images/products/Product3.jpg",
      kante: "Gerade",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Fein",
    },
    {
      id: 11,
      slug: "eckbank-studio",
      name: "Eckbank Studio",
      summary: "Grosszugige Banklosung mit warmer Holzprasenz.",
      price: 2940,
      discount: null,
      configurable: false,
      image: "/images/products/Product4.jpg",
      kante: "Baumkante",
      gestell: "Natur",
      lack: "Geölt",
      buerstung: "Gebürstet",
    },
    {
      id: 12,
      slug: "bank-kompakt",
      name: "Bank Kompakt",
      summary: "Kleineres Sitzobjekt mit klarer Geometrie und robuster Basis.",
      price: 1690,
      discount: 6,
      configurable: false,
      image: "/images/products/Product5.jpg",
      kante: "Gerade",
      gestell: "Schwarz",
      lack: "Seidenmatt",
      buerstung: "Fein",
    },
  ],
  bed: [
    {
      id: 13,
      slug: "bett-eiche",
      name: "Bett Eiche",
      summary: "Reduziertes Holzrahmenbett mit warmer Maserung.",
      price: 5390,
      discount: 9,
      configurable: false,
      image: "/images/products/Product8.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Geölt",
      buerstung: "Fein",
    },
    {
      id: 14,
      slug: "rahmenbett-nord",
      name: "Rahmenbett Nord",
      summary: "Klarer Aufbau mit ruhiger Kopfteilzeichnung.",
      price: 5980,
      discount: null,
      configurable: false,
      image: "/images/products/Product7.jpg",
      kante: "Gerade",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Gebürstet",
    },
    {
      id: 15,
      slug: "bett-atelier",
      name: "Bett Atelier",
      summary: "Modernes Holzbett mit feiner Kante und ruhigem Ausdruck.",
      price: 5640,
      discount: null,
      configurable: false,
      image: "/images/products/Product6.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Seidenmatt",
      buerstung: "Fein",
    },
    {
      id: 16,
      slug: "bett-form",
      name: "Bett Form",
      summary: "Massiver Rahmen mit dunklerem Ton und klarer Silhouette.",
      price: 6210,
      discount: 13,
      configurable: false,
      image: "/images/products/Product8.jpg",
      kante: "Baumkante",
      gestell: "Schwarz",
      lack: "Matt",
      buerstung: "Gebürstet",
    },
    {
      id: 17,
      slug: "schlafsystem-werk",
      name: "Schlafsystem Werk",
      summary: "Reduzierte Schlaflosung mit handwerklicher Materialnote.",
      price: 5870,
      discount: 11,
      configurable: false,
      image: "/images/products/Product7.jpg",
      kante: "Gerade",
      gestell: "Natur",
      lack: "Geölt",
      buerstung: "Gebürstet",
    },
  ],
};

export const filterLabels: Record<FilterKey, string> = {
  kante: "Kante",
  gestell: "Gestell",
  lack: "Lack",
  buerstung: "Bürstung",
};
